# Generated by Django 3.0.5 on 2020-05-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name_plural': 'Searches'},
        ),
        migrations.RenameField(
            model_name='search',
            old_name='Search',
            new_name='search',
        ),
    ]
